### ISSUE TITLE
caProvider: Request for part of structure field returns whole structure

### ISSUE THREAD

**Issue by dhickin** [epics-base/pvAccessCPP#42] opened 2016-03-29 14:34 UTC
When doing a channel get or monitor with a request for part of a structure field caProvider provides the whole structure:

For example do a pvget, pvget -m or eget and fetch part of the alarm:
```
$ eget -ir "field(value,alarm.severity)"  ca:///double01
double01
epics:nt/NTScalar:1.0 
    double value 0
    alarm_t alarm
        int severity 3
        int status 3
        string message UDF_ALARM
```

Similarly for other fields.

**Comment by dhickin** [comment] 2016-03-29 14:37
In particular this also applies to the value field of an enum pv:
```
eget -ir "field(value.index)"  ca:///enum01
enum01
epics:nt/NTEnum:1.0 
    enum_t value
        int index 0
        string[] choices [zero,one,two,three]
```

**Comment by msekoranja** [comment] 2016-03-29 14:57
Duplicate of #41

**Comment by dhickin** [comment] 2016-03-29 16:14
I opened as a separate issue to #41 as these could easily end up being done as orthogonal fixes. Pruning the subfields of alarm, timeStamp structures can be done independently of a fix to supply the correct top-level subfields. There's no technical issue in fixing these unlike the case with #41 - it's just a pain in this instance.

**Closed** 2016-05-19 13:33 UTC
